# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.202.5/containers/java-8/.devcontainer/base.Dockerfile

# [Choice] Debian OS version (use bullseye on local arm64/Apple Silicon): buster, bullseye
FROM clojure:openjdk-8

RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "jq"]